Assignment 4, Aslan Smagulov

In [ ]:
import numpy as np
import random as rn


In [354]:
B=np.random.rand(3,3)
print(B)




[[ 0.12554957  0.95203407  0.5654395 ]
 [ 0.10788745  0.61342967  0.72420066]
 [ 0.60365391  0.16071893  0.73760789]]


In [352]:
import math
print (value for value in B if not math.isnan(value))
u=np.zeros([3,3],dtype=np.float)
l=np.zeros([3,3],dtype=np.float)


for i in range(0,2):
    for j in range(0,2):
        B[i][j]=(float(B[i][j]))
        u[i][j]=B[i][j]
for k in range(0,2) :
    for i in range(0,2):
        if (k==i):
            l[k][i]=1
        if (k<i):
            factor=(B[i][k])/(B[k][k])
            l[i][k]=factor
            for n in range(0,2):
                B[i][n]=B[i][n]-(factor*B[k][i])
                u[i][n]=B[i][n]
print(l)
print(u)
I=np.zeros([3,3])
for i in range (0,2):
    for j in range (0,2):
        if (i==j):
            I[i][j]=1
        else :
            I[i][j]=0
print(I)
X=np.zeros([3,3])
sum=0
for k in range (0,2):
    for i in range (0,2):
        for j in range (0,2):
            sum=sum+X[j][k]*(l[i][j])
            (I[i][k])=sum
            
Inverse=np.zeros([3,3])
for k in range (0,2):
    for i in range (0,2):
        for j in range (0,2):
            sum=sum+Inverse[j][k]*(u[i][j])
            (X[i][k])=sum     
print(X)
print(Inverse)
#unfortunately, I could not fix the problem since it gives incorrect inverse matrix, although the algorithm above should work

<generator object <genexpr> at 0x078D2420>
[[ 1.          0.          0.        ]
 [ 0.23217481  1.          0.        ]
 [ 0.          0.          0.        ]]
[[ 0.60450703  0.24747589  0.        ]
 [ 0.08289363  0.11385142  0.        ]
 [ 0.          0.          0.        ]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [355]:
inverse=np.linalg.inv(B)
print(inverse)
print(np.linalg.cond(B))

[[ 1.83595918 -3.33974896  1.87162394]
 [ 1.95346681 -1.35875091 -0.16344589]
 [-1.92818307  3.0292918  -0.14037847]]
9.44080576743


The matrix is well-conditioned as the condition number is not large or infinity